version: "3"
services:
  web:
    build: .
    volumes:
      - .:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mongo
    links: 
      - "mongo:mongo"

  mongo:
    image: mongo
    container_name: mongo
    volumes:
        - ./db:/data/db
    ports:
        - "27017:27017"

  mongoseed:
    image: mongo
    container_name: "phpmongoseed"
    links:
            - "mongo:mongo"
    depends_on:
      - mongo
    volumes:
            - ./dbseed:/dbseed
    command: mongorestore --uri "mongodb://mongo:27017" -d biddersstop /dbseed/biddersstop